// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTOP__SYMS_H_
#define VERILATED_VTOP__SYMS_H_  // guard

#include "verilated.h"
#include "verilated_vcd_c.h"

// INCLUDE MODEL CLASS

#include "Vtop.h"

// INCLUDE MODULE CLASSES
#include "Vtop___024root.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)Vtop__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vtop* const __Vm_modelp;
    bool __Vm_dumping = false;  // Dumping is active
    VerilatedMutex __Vm_dumperMutex;  // Protect __Vm_dumperp
    VerilatedVcdC* __Vm_dumperp VL_GUARDED_BY(__Vm_dumperMutex) = nullptr;  /// Trace class for $dump*
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vtop___024root                 TOP;

    // SCOPE NAMES
    VerilatedScope __Vscope_TOP;
    VerilatedScope __Vscope_gpu;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__decoder_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__fetcher_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__unnamedblk1;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__unnamedblk2;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__unnamedblk2__unnamedblk3;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__divergence_stack_gen__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__divergence_stack_gen__BRA__0__KET____divergence_stack_inst;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__divergence_stack_gen__BRA__0__KET____divergence_stack_inst__unnamedblk1;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk1;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk2;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk3;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk3__unnamedblk4;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk5;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk5__unnamedblk6;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk7;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk8;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__threads__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__threads__BRA__0__KET____register_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__threads__BRA__1__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__threads__BRA__1__KET____register_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__threads__BRA__2__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__threads__BRA__2__KET____register_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__threads__BRA__3__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__threads__BRA__3__KET____register_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__0__KET____alu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__0__KET____lsu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__0__KET____pc_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__1__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__1__KET____alu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__1__KET____lsu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__1__KET____pc_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__2__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__2__KET____alu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__2__KET____lsu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__2__KET____pc_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__3__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__3__KET____alu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__3__KET____lsu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warps__BRA__3__KET____pc_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warptothreadbus_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warptothreadbus_instance__unnamedblk1;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warptothreadbus_instance__unnamedblk2;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____core_instance__warptothreadbus_instance__unnamedblk3;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____genblk1__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____genblk1__BRA__1__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____genblk1__BRA__2__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__0__KET____genblk1__BRA__3__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__decoder_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__fetcher_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__unnamedblk1;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__unnamedblk2;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__unnamedblk2__unnamedblk3;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__divergence_stack_gen__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__divergence_stack_gen__BRA__0__KET____divergence_stack_inst;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__divergence_stack_gen__BRA__0__KET____divergence_stack_inst__unnamedblk1;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk1;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk2;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk3;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk3__unnamedblk4;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk5;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk5__unnamedblk6;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk7;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__scheduler_instance__warp_manager_instance__unnamedblk8;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__threads__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__threads__BRA__0__KET____register_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__threads__BRA__1__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__threads__BRA__1__KET____register_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__threads__BRA__2__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__threads__BRA__2__KET____register_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__threads__BRA__3__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__threads__BRA__3__KET____register_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__0__KET____alu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__0__KET____lsu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__0__KET____pc_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__1__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__1__KET____alu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__1__KET____lsu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__1__KET____pc_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__2__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__2__KET____alu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__2__KET____lsu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__2__KET____pc_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__3__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__3__KET____alu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__3__KET____lsu_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warps__BRA__3__KET____pc_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warptothreadbus_instance;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warptothreadbus_instance__unnamedblk1;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warptothreadbus_instance__unnamedblk2;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____core_instance__warptothreadbus_instance__unnamedblk3;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____genblk1__BRA__0__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____genblk1__BRA__1__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____genblk1__BRA__2__KET__;
    VerilatedScope __Vscope_gpu__cores__BRA__1__KET____genblk1__BRA__3__KET__;
    VerilatedScope __Vscope_gpu__data_memory_controller;
    VerilatedScope __Vscope_gpu__data_memory_controller__unnamedblk1;
    VerilatedScope __Vscope_gpu__data_memory_controller__unnamedblk2;
    VerilatedScope __Vscope_gpu__data_memory_controller__unnamedblk2__unnamedblk3;
    VerilatedScope __Vscope_gpu__dcr_instance;
    VerilatedScope __Vscope_gpu__dispatch_instance;
    VerilatedScope __Vscope_gpu__dispatch_instance__unnamedblk1;
    VerilatedScope __Vscope_gpu__dispatch_instance__unnamedblk2;
    VerilatedScope __Vscope_gpu__dispatch_instance__unnamedblk3;
    VerilatedScope __Vscope_gpu__dispatch_instance__unnamedblk4;
    VerilatedScope __Vscope_gpu__program_memory_controller;
    VerilatedScope __Vscope_gpu__program_memory_controller__unnamedblk1;
    VerilatedScope __Vscope_gpu__program_memory_controller__unnamedblk2;
    VerilatedScope __Vscope_gpu__program_memory_controller__unnamedblk2__unnamedblk3;

    // SCOPE HIERARCHY
    VerilatedHierarchy __Vhier;

    // CONSTRUCTORS
    Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp);
    ~Vtop__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
    void _traceDump();
    void _traceDumpOpen();
    void _traceDumpClose();
};

#endif  // guard
