// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"
#include "Vtop__Syms.h"
#include "Vtop___024root.h"

// Parameter definitions for Vtop___024root
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__IDLE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__READ_WAITING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__WRITE_WAITING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__READ_RELAYING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__WRITE_RELAYING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__IDLE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__READ_WAITING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__WRITE_WAITING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__READ_RELAYING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__WRITE_RELAYING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__fetcher_instance__DOT__IDLE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__fetcher_instance__DOT__FETCHING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__fetcher_instance__DOT__FETCHED;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__NOP;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__BRnzp;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__CMP;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__ADD;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__SUB;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__MUL;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__DIV;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__LDR;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__STR;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__CONST;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__decoder_instance__DOT__RET;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__READY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__STALL;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__MASKED;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__SCHEDULED;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__IDLE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__FETCH;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__DECODE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__REQUEST;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__WAIT;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__EXECUTE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__UPDATE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__DONE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__alu_instance__DOT__ADD;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__alu_instance__DOT__SUB;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__alu_instance__DOT__MUL;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__alu_instance__DOT__DIV;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__lsu_instance__DOT__IDLE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__lsu_instance__DOT__REQUESTING;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__lsu_instance__DOT__WAITING;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__lsu_instance__DOT__DONE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__alu_instance__DOT__ADD;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__alu_instance__DOT__SUB;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__alu_instance__DOT__MUL;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__alu_instance__DOT__DIV;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__lsu_instance__DOT__IDLE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__lsu_instance__DOT__REQUESTING;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__lsu_instance__DOT__WAITING;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__lsu_instance__DOT__DONE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__ARITHMETIC;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__MEMORY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__CONSTANT;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__ARITHMETIC;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__MEMORY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__CONSTANT;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__ARITHMETIC;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__MEMORY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__CONSTANT;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__ARITHMETIC;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__MEMORY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__CONSTANT;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__fetcher_instance__DOT__IDLE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__fetcher_instance__DOT__FETCHING;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__fetcher_instance__DOT__FETCHED;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__NOP;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__BRnzp;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__CMP;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__ADD;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__SUB;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__MUL;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__DIV;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__LDR;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__STR;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__CONST;
constexpr CData/*3:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__decoder_instance__DOT__RET;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__READY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__STALL;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__MASKED;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__SCHEDULED;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__IDLE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__FETCH;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__DECODE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__REQUEST;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__WAIT;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__EXECUTE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__UPDATE;
constexpr CData/*2:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__DONE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__alu_instance__DOT__ADD;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__alu_instance__DOT__SUB;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__alu_instance__DOT__MUL;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__alu_instance__DOT__DIV;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__lsu_instance__DOT__IDLE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__lsu_instance__DOT__REQUESTING;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__lsu_instance__DOT__WAITING;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__lsu_instance__DOT__DONE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__alu_instance__DOT__ADD;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__alu_instance__DOT__SUB;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__alu_instance__DOT__MUL;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__alu_instance__DOT__DIV;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__lsu_instance__DOT__IDLE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__lsu_instance__DOT__REQUESTING;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__lsu_instance__DOT__WAITING;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__lsu_instance__DOT__DONE;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__ARITHMETIC;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__MEMORY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__CONSTANT;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__ARITHMETIC;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__MEMORY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__CONSTANT;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__ARITHMETIC;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__MEMORY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__CONSTANT;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__ARITHMETIC;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__MEMORY;
constexpr CData/*1:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__CONSTANT;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__DATA_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__DATA_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__DATA_MEM_NUM_CHANNELS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__PROGRAM_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__PROGRAM_MEM_NUM_CHANNELS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__NUM_CORES;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__NUM_LSUS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__NUM_FETCHERS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__lsu_index;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__lsu_index;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__lsu_index;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__lsu_index;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__NUM_CONSUMERS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__NUM_CHANNELS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__data_memory_controller__DOT__WRITE_ENABLE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__NUM_CONSUMERS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__NUM_CHANNELS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__program_memory_controller__DOT__WRITE_ENABLE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__dispatch_instance__DOT__NUM_CORES;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__dispatch_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__DATA_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__DATA_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__PROGRAM_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__fetcher_instance__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__fetcher_instance__DOT__PROGRAM_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__warp_manager_instance__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__warp_manager_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__scheduler_instance__DOT__warp_manager_instance__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warptothreadbus_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warptothreadbus_instance__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warptothreadbus_instance__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__pc_instance__DOT__DATA_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__pc_instance__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__pc_instance__DOT__DATA_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__pc_instance__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__THREAD_ID;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__THREAD_ID;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__THREAD_ID;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__THREAD_ID;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__0__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__DATA_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__DATA_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__PROGRAM_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__fetcher_instance__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__fetcher_instance__DOT__PROGRAM_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__warp_manager_instance__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__warp_manager_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__scheduler_instance__DOT__warp_manager_instance__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warptothreadbus_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warptothreadbus_instance__DOT__THREADS_PER_WARP;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warptothreadbus_instance__DOT__WARPS_PER_CORE;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__pc_instance__DOT__DATA_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__0__KET____DOT__pc_instance__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__pc_instance__DOT__DATA_MEM_DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__warps__BRA__1__KET____DOT__pc_instance__DOT__PROGRAM_MEM_ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__THREAD_ID;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__0__KET____DOT__register_instance__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__THREAD_ID;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__1__KET____DOT__register_instance__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__THREAD_ID;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__2__KET____DOT__register_instance__DOT__DATA_BITS;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__THREAD_ID;
constexpr IData/*31:0*/ Vtop___024root::gpu__DOT__cores__BRA__1__KET____DOT__core_instance__DOT__threads__BRA__3__KET____DOT__register_instance__DOT__DATA_BITS;


void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf);

Vtop___024root::Vtop___024root(Vtop__Syms* symsp, const char* v__name)
    : VerilatedModule{v__name}
    , vlSymsp{symsp}
 {
    // Reset structure values
    Vtop___024root___ctor_var_reset(this);
}

void Vtop___024root::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

Vtop___024root::~Vtop___024root() {
}
